services:

  traefik:
    container_name: "traefik"
    image: "traefik"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "--accesslog"
      - "--log"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

  app:
    container_name: "app"
    build: .
    env_file:
      - ".env"
    volumes:
      - ".:/code"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"

  redis:
    container_name: "redis"
    image: "redis"

  worker:
    container_name: "worker"
    build: .
    env_file:
      - ".env"
    command: "celery -A app.worker worker -B --loglevel=info"

#  flower:
#    container_name: "flower"
#    image: "mher/flower"
#    command: "--url_prefix=flower"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.flower.loadbalancer.server.port=5555"
#      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
#      - "traefik.http.routers.flower.entrypoints=web"
#      - "traefik.http.routers.flower.middlewares=flower_auth"
#      - "traefik.http.middlewares.flower_auth.basicauth.users=${FLOWER_BASICAUTH}"

  dozzle:
    container_name: "dozzle"
    image: "amir20/dozzle"
    environment:
      - "DOZZLE_BASE=/logs"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.rule=Host(`localhost`) && PathPrefix(`/logs`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.routers.dozzle.middlewares=dozzle_auth"
      - "traefik.http.middlewares.dozzle_auth.basicauth.users=${DOZZLE_BASICAUTH}"
