services:

  traefik:
    container_name: "traefik"
    image: "traefik:v2.10"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "--accesslog"
      - "--log"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

  app:
    container_name: "app"
    build: .
    restart: "always"
    env_file:
      - ".env"
    volumes:
      - .:/code
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.routers.app.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=web"

  redis:
    container_name: "redis"
    image: "redis:7.2"
    restart: "always"

  worker:
    container_name: "worker"
    depends_on:
      - "redis"
    build: .
    restart: "always"
    env_file:
      - ".env"
    command: "celery -A app.worker worker -B --loglevel=info"

  flower:
    container_name: "flower"
    depends_on:
      - "redis"
    image: "mher/flower:latest"
    restart: "always"
    env_file:
      - ".env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.middlewares=flower_auth"
      - "traefik.http.middlewares.flower_auth.basicauth.users=${FLOWER_BASICAUTH}"
