services:

  backend:
    container_name: app
    image: ghcr.io/julienpillaud/levindorge:${IMAGE_TAG}
    restart: always
    networks:
      - traefik-public
      - internal
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.backend.loadbalancer.server.port=8000

      - traefik.http.routers.backend-http.rule=Host(`${HOST?Variable not set}`)
      - traefik.http.routers.backend-http.entrypoints=http

  worker:
    container_name: worker
    image: ghcr.io/julienpillaud/levindorge:${IMAGE_TAG}
    restart: always
    command: faststream run app.core.event_handler:app --log-config app/core/logging/config.json
    networks:
      - internal
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:8.2
    restart: always
    networks:
      - internal

networks:
  traefik-public:
    external: true
  internal:
    driver: bridge
